# Generated by Django 3.2.2 on 2021-08-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20210830_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='type',
            new_name='assignment_type',
        ),
    ]
