# Generated by Django 3.2.6 on 2021-08-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_subjects_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='submission_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='assignment_student',
            name='assignment_pdf',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='assignment_student',
            name='submitted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
