# Generated by Django 3.2.6 on 2021-08-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_auto_20210831_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_student',
            name='submitted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
